version: 2

build:
  image: latest

# Build PDF
formats:
  - pdf

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: python
  system_packages: true