version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - python -m pip install --no-cache-dir pip setuptools<58.3.0
      - python -m pip install --no-cache-dir pybind11[global]
      - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
      - python -m pip install . -v

# Build PDF
formats:
  - pdf
