comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

flag_management:
  default_rules:
    carryforward: true
  rpackage:
    paths:
      - R-package
  python:
    ignore:
      - "python/include/"
      - "python/src/abess_wrap.cpp"
      - "python/abess/cabess"
    

  
